### ISSUE TITLE
low to no difference, between upscaled and IterativeMixer

### ISSUE THREAD

**Issue by FilipAndersson245** [ttulttul/ComfyUI-Iterative-Mixer#14]
Hello, im trying out your node, as it seem very interesting, but I am unable to get any significant improvement in quality, I tested earlier today and the output where almost identical, and now when I'm trying it seem to just produce a lower quality image.

Am I doing something wrong?
![image](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/17986183/4e17cb6f-bea9-482a-a660-f2193a3233d4)

**Comment by FilipAndersson245** [comment]
I tested to plot the difference for one color channel and the result fell quite underwhelming, I belive I'm doing something wrong
![image](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/17986183/3d6f5c36-abeb-476a-8834-9f54d77a7db1)

**Comment by ttulttul** [comment]
Try these settings:
<img width="466" alt="image" src="https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/852933/6bcd881f-f94f-474e-b29a-ae46ee99def8">

**Comment by ttulttul** [comment]
The two most powerful settings are `blend_max` and `perlin_strength`. Reduce `blend_max` to allow the model to spend the last part of diffusion without any guidance from the original latent - this can help to increase the creativity and richness of the output, at the cost of reducing consistency. If you use the `euler_perlin` sampler and increase `perlin_strength` then the sampler will, after each step of iterative mixing, do a second de-noise pass using a random mask generated from perlin noise. The perlin noise masking can really help.

I noticed you are using the dpmpp_2m sampler. I should note that I have not gotten good results from that sampler. I have spent most of my time working with the Euler sampler.

**Comment by ttulttul** [comment]
Update: The euler_perlin mode wasn't making the difference I thought it was, so I no longer recommend it. Instead, try these settings:

sample: euler
alpha_1: 0.5 to 2.4; lower values give the model more freedom
stop_blending_at: 0.7-1.0; lower numbers give the model dramatically more freedom.

Use a lot of steps - like 60-80 steps with Euler/normal. And use a denoise strength of 1.0. Using a lower denoise is fine, but in an upscale it tends to lead to blurred output.
