### ISSUE TITLE
Impossible to follow the instructions about the advanced scheduler node

### ISSUE THREAD

**Issue by KerfuffleV2** [ttulttul/ComfyUI-Iterative-Mixer#21]
>  For instance, if you set `steps` to `40` and `start_at_step` to `0` and `end_at_step` to `20` (i.e. 50% of the way through the total steps), then you must adjust `stop_blending_at` to `80` so that the blending schedule will be stretched horizontally by a factor of two

However, the nodes take percentages not specific step numbers so there is only `stop_blending_at_pct`. Do you mean we should set `stop_blending_at_pct` here to `2.0`? It's also not clear what settings should be used for the second mixing sampler you suggest using. I did try with `2.0` but didn't manage to get decent results.

I've actually gotten the best results not even using the iterative mixing scheduler and something like this:

![image](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/44031344/e73ca283-ad2a-4d9d-938c-f149fea0ec81)

Then injecting a little extra perlin noise and running more steps with a normal sampler. The suggested iterative mixing settings all seem to remove a lot of detail from the image and smooth everything out.

**Comment by ttulttul** [comment]
I am sorry for the poor documentation. I'll update the README. Please check back there momentarily.

**Comment by KerfuffleV2** [comment]
@ttulttul I am confused about why this was closed. It still isn't possible to follow the instructions in the README and there haven't been any updates to it since then. The README talks about using step-based values when the nodes actually have percent-based ones so it isn't clear if it's even possible to fix it from the user perspective.

I'm not trying to rush you or anything, so if you just didn't have time to update it or whatever that is certainly perfectly fine but it still is a legitimate issue which probably should remain open.
