### ISSUE TITLE
issue Overpainting.json

### ISSUE THREAD

**Issue by salisbury-espinosa** [ttulttul/ComfyUI-Iterative-Mixer#24]
TypeError: KSamplerX0Inpaint.__init__() takes 2 positional arguments but 3 were given

**Comment by ttulttul** [comment]
Yeah, sorry about that. It was a momentary issue that has been fixed.

**Comment by ttulttul** [comment]
ComfyUI added some more parameters to that class's `__init__` and I had to add those.
