### ISSUE TITLE
Iterative Mixer K-sampler node doesn't seem to do anything

### ISSUE THREAD

**Issue by Miteas** [ttulttul/ComfyUI-Iterative-Mixer#4]
I've tried copying your workflow with sdxl instead of 1.5, the node doesn't seem to be doing anything. It just passes the latent straight through to the next step. 
The decoded latent upscaled with the NN upscaler, and the one subsequently ran through the node are identical. I've tried playing with all the parameters and can't get it to work. 

I get this warning in my command prompt when running the model,

WARNING:root:dimension at output is torch.Size([1, 4, 256, 256])

But I don't think it is related.

**Comment by ttulttul** [comment]
The warning isn't a problem; it should be removed and is a leftover from early development. I have not tested this node with SDXL and will try to do so soon. Theoretically, the model should not matter, but the devil is in the details.

**Comment by elphamale** [comment]
Yeah, it seems the node doesn't do anything with SDXL.

**Comment by Miteas** [comment]
I managed to get it working on my install. Basically had to do a comfyui reinstall, and it eventually worked. But I haven't had good results with sdxl. Maybe someone else has.

**Comment by ttulttul** [comment]
Stand by for a major new release, which implements the mixing algorithm using a custom sampler node. The new approach produces noiseless output that is well aligned with the source latent.

**Comment by ttulttul** [comment]
Please try the new release. Use the IterativeMixingSampler as per the new example workflow.

**Comment by Miteas** [comment]
Just tested it, works great, well done fantastic work. The only strange thing is that I used your custom workflow with an sdxl model and it produced 11 identical output images for iterative mixing output. To be clear the samplercustom ran 11 separate times from one latent image. The rough upscale and the K-sampler upscale sections produce only one image each.

**Comment by Miteas** [comment]
My mistake, they aren't identical.

**Comment by ttulttul** [comment]
Hmmm if you are getting 11 batch outputs from an SDXL model then I must be screwing up tensors somewhere. I'll give it a try.

**Comment by ttulttul** [comment]
> My mistake, they aren't identical.

Even if they aren't identical, the SamplerCustom isn't meant to emit batches unless you feed it a batch latent input. So that's the strange bit.
