### ISSUE TITLE
last update messed up the iterative ksampler setup for me

### ISSUE THREAD

**Issue by if-ai** [ttulttul/ComfyUI-Iterative-Mixer#7]
here is the error ERROR:root:Failed to validate prompt for output 1043:
ERROR:root:* Iterative Mixing KSampler 874:
ERROR:root:  - Required input is missing: stop_blending_at_pct
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 756:
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1007:2:
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 808:
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1044:
ERROR:root:* Iterative Mixing KSampler 1020:
ERROR:root:  - Required input is missing: stop_blending_at_pct
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 914:
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 1054:2:
ERROR:root:Output will be ignored

**Comment by if-ai** [comment]
sorry false alarm refreshing again and it picked up thanks

**Comment by ttulttul** [comment]
Glad to hear you figured it out!
